name: pylint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run-pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
          with:
            python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          python install -r requirements.txt
      - run: |
          pylint --load-plugins pylint_django --django-settings-module=example.settings **/*.py
